on:
  release:
    types: [published]

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    name: modex-iteration-cloud-pw
    steps:
      - name: run-workflow
        id: run-cloud-pw
        uses: parallelworks/test-workflow-action@v5
        with:
          pw-user-host: 'cloud.parallel.works'
          pw-api-key: ${{ secrets.PW_API_KEY }}
          pw-user: 'sfgary'
          resource-pool-names: 'cloud'
          workflow-name: 'sl_core'
          workflow-parameters: '{"repos|ml_arch_repo": "git@github.com:parallelworks/dynamic-learning-rivers", "repos|ml_arch_branch": test-ml-workflow", "repos|push_to_gh": "True", "repos|ml_code_repo": "https://github.com/parallelworks/sl_core", "repos|ml_data_repo": "https://github.com/parallelworks/global-river-databases", "repos|whost": "cloud.clusters.pw", "repos|miniconda_loc": "/home/__USER__/.miniconda3", "repos|my_env": "superlearner", "superlearner|train_test_data": "input_data/whondrs_25_inputs_train.csv", "superlearner|predict_data": "scripts/WH_RA_GL_global_predict_25_inputs", "superlearner|num_inputs": "25", "superlearner|superlearner_conf": "sample_inputs/superlearner_conf.py", "superlearner|work_dir_base": "ml_models/sl_", "superlearner|hpo": "True", "superlearner|cross_val_score": "False", "superlearner|smogn": "False", "superlearner|onnx": "False", "superlearner|backend": "loky", "superlearner|n_jobs": "8"}'
