on:
  release:
    types: [published]

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    name: modex-iteration-cloud-pw
    steps:
      - name: run-workflow
        id: run-cloud-pw
        uses: parallelworks/test-workflow-action@v5
        with:
          pw-user-host: 'cloud.parallel.works'
          pw-api-key: ${{ secrets.PW_API_KEY }}
          pw-user: 'sfgary'
          resource-pool-names: 'cloud'
          workflow-name: 'sl_core'
          workflow-parameters: '{"commands|ml_arch_repo": "git@github.com:parallelworks/dynamic-learning-rivers", "commands|ml_arch_branch": "modex_ordered_add", "commands|ml_code_repo": "https://github.com/parallelworks/sl_core", "commands|ml_data_repo": "https://github.com/parallelworks/global-river-databases", "commands|whost": "cloud.clusters.pw", "commands|miniconda_loc": "/home/__USER__/.miniconda3", "commands|my_env": "superlearner", "commands|train_test_data": "input_data/whondrs_25_inputs_train.csv", "commands|predict_data": "scripts/WH_RA_GL_global_predict_25_inputs", "commands|num_inputs": "25", "commands|superlearner_conf": "sample_inputs/superlearner_conf.py", "commands|work_dir_base": "ml_models/sl_", "commands|hpo": "True", "commands|cross_val_score": "False", "commands|smogn": "False", "commands|onnx": "False", "commands|backend": "loky", "commands|n_jobs": "8"}'
